better_figures_and_images: handle missing files due to Unicode
Before, we got an unhelpful crash when a file can't be found due to a
Unicode character in the name:

ERROR: Could not process ./2014-12-24-incubator-final.md
'ascii' codec can't encode character u'\xc2' in position 67: ordinal not in range(128)

After:

ERROR: Could not process ./2014-12-24-incubator-final.md
[Errno 2] No such file or directory: u'/Users/dhalperi/Code/blog/content/images/2014-12-04-fall-incubator-\xc2Katsuyama.JPG'

Reference: https://github.com/getpelican/pelican-plugins/pull/381